### ISSUE TITLE
dm9x0 LCD/Skin

### ISSUE THREAD

**Issue by persianpros** [DMM-PLi/meta-dream#14]
We need to take a deep look at these files:
https://github.com/openatv/enigma2/blob/6.1/lib/gdi/lcd.cpp
https://github.com/openatv/enigma2/blob/6.1/lib/gdi/lcd.h

**Comment by UrmasP** [comment]
Today still issue with dm900. Look st hete: http://dreambox.de/board/index.php?thread/21202-frontprocessor-version-6/
Can you somehow check the drivers for dm9x0, what we currently using?

**Comment by persianpros** [comment]
I didn't commit anything about LCD yet ...

**Comment by UrmasP** [comment]
Okay, well, at the moment the error like this with led (blue, or red, or pink). Led is located next to the LCD. Probably the management is made in software drivers, I do not know. About Skins, at the moment is faulty PLi-HD. At the same time Pli-FullHD is OK. The error is, that in case PLi-HD needs activation from little screen any second restart or after boot. I have never such thing before seen, and even is hard to describe that.

**Comment by UrmasP** [comment]
Here is an example of the LED, and that we have today in the indeterminate.
http://www.youtube.com/watch?v=JeEXdZHINz0

**Comment by Hains** [comment]
Tomorrow i will add 'fsbupdater' and 'frame buffer fix' from OpenATV into meta-dream.
Also try to fix build kodi.

About configuration triple tuner. OpenPLi has no proper triple tuner support  yet.
It's not dmm related.So hopefully we can expect support from OpenPLi?

Then everything should be alright.

**Comment by persianpros** [comment]
What do we need for triple tuner? point me to the sources please (like OpenATV's enigma2) maybe I can make merge requests ...

**Comment by UrmasP** [comment]
Dimitrij, athoik and Hains should put together, and to figure out this code. The key is in the files /usr/lib/enigma2/python/Components/UsageConfig.py , NimManager.py, and maybe a few more files. This Python code cannot be 1:1 copy / paste because it in atv strongly different. ATV code is more clumsy, but also the PLi is a far from ideal. It seems to me that Hains knows what is wrong in the code, but the enigma2 where it is exactly, and this in its own way, copy from atv is a good challenge. There may also be a part of the code in the cpp, I'm not sure yet.

**Comment by Hains** [comment]
Problem with triple tuner 2xsvb-s2/1xdvb-c is(what i understand from testers), you can't disable/enable each tuner separately. If you disable one dvb-s2 tuners, all tuners are switched off. So it's all or nothing.
Settings are not being saved in enigma2 for each tuner.
I think it's due to the combination of dvb-s2 and dvb-c. Because twin tuners 2xdvb-s2 or 2xdvb-c is ok.
Somewhere in code nimmanager.py, usageconfig.py, frondend.cpp is a check 
' if tuner is multi_type and compatible with dvb-c/dvb-t' all tuners are switched off, which is normally for twin dvb-c/dvb-t tuners.
Enabling all tuners  is a problem when e.g. one dvb-s2 tuner is not connected to dish.

If can't find a specific commit in github OpenATV,

**Comment by Hains** [comment]
Now i'm done with it...@UrmasP stop sending PM to Dimitrij, Athoik etc.

**Comment by Hains** [comment]
If we need help or more information we will ask question at OpenPLi forum or Persian Prince/MastaG will contact OpenPLi-dev's.

**Comment by persianpros** [comment]
Give me some time to investigate ATV's sources ...
