### ISSUE TITLE
Kodi support

### ISSUE THREAD

**Issue by persianpros** [DMM-PLi/meta-dream#3]
dm7080/dm820/dm900 could use kodi but what's the status in PLi's OE?
Can Open PLi images support kodi?

**Comment by Hains** [comment]
Kodi broken in rocko branch. kodi support dropped for dm7080, dm820, dm900 and dm920.

**Comment by Hains** [comment]
We need to update unpnp with debian patches. I have them(also in openpli-oe-core) and i will add them these days.
djmount fails to compile due to wrong API (lib)upnp, and kodi has also to do with it.
For ARM boxes we need to bypass the required MACHINE_FEATURS = "opengl" in kodi_1.7.bb
with bbappend as workaround. I see no other option for now.

**Comment by Hains** [comment]
Kode building fine now in pyro branch. For now, i must copy kodi from meta-openembedded to meta-dream.
Also ffmpeg in openpli-oe-core is not not ok. It doesn't place the required static libraries libavcodec.a, libswscale.a etc. in build/temp/sysroots-components.
I used my own ffmpeg recipe ,which build from git, but that version does break gstreamer-libav and exteplayer.

I copy kodi to meta-dream this afternoon/evening anyway. With the required changes.
For ffmpeg i'm still busy.
