### ISSUE TITLE
PATCHLEVEL upgrade for kernel 3.2

### ISSUE THREAD

**Issue by persianpros** [DMM-PLi/meta-dream#7]
I did upgrade kernel 3.2 to PATCHLEVEL 75 before: https://github.com/DMM-PLi/meta-dream/commit/136602b8ee418461cb3939ecc40a0e90b39bca85 but recent patches won't work unless we edit linux-dreambox-3.2-3c7230bc0819495db75407c365f4d1db70008044.patch

New patches are here: https://cdn.kernel.org/pub/linux/kernel/v3.x/ just search for "patch-3.2."

**Comment by Hains** [comment]
I have patch for dreambox-kernel. We need to make that patch local, just as the other pacthes.
Since patchlevel 84 unionfs also need a patch.
I Can upgrade to 3.2.90. I will do that these days..
Patchlevel 91 has memory leaks, which causing the box hang/stuck/slow..Within 24 hours after reboot.
But i'm not 100% sure it's kernel.

**Comment by Hains** [comment]
See 

https://github.com/Hains/openpli-oe-core/commits/master-next/meta-dream/recipes-bsp/linux
